EXPIRATION = "expiration"
BID = "bid"
ASK = "ask"
MID = "mid"
BID_ASK_SPREAD = "bid_ask_spread"
STRIKE = "strike"
RIGHT = "right"
ASK_SIZE = "ask_size"
BID_SIZE = "bid_size"
VOLUME = "volume"
SYMBOL = "symbol"
CLOSE = "close"

PUT = "PUT"
CALL = "CALL"

FORWARD = "forward"
TTM = "ttm"
BID_DIFF = "bid_diff"
ASK_DIFF = "ask_diff"
